
[General]
	#Chance of Jolly Boxes to spawn when you sleep (Set to 0 to disable spawning)
	#Range: 0.0 ~ 1.0
	present_chance = 1.0
	#Minimum amount of presents that can spawn
	#Range: 0 ~ 32
	present_minimum = 1
	#Maximum amount of presents that can spawn
	#Range: 0 ~ 32
	present_maximum = 5
	#Should Presents only spawn in snowy biomes?
	only_in_snowy_biomes = false
	#Should Presents only spawn during December?
	only_in_december = false
	#Replace the Sleigh Bell sound with a Party Horn sound?
	party_horn_replace_bells = false
	#Replace the Sleigh Bell sound with a Party Horn sound (December excluded)?
	party_horn_december = false

